app/catalog/models.py
from app import db
from datetime import datetime


class Publication(db.Model):
    __tablename__ = 'publication'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return 'Publisher Name is {}'.format( self.name)


class Book(db.Model):
    __tablename__ = 'book'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(500), nullable=False, index=True)
    author = db.Column(db.String(350))
    avg_rating = db.Column(db.Float)
    format = db.Column(db.String(50))
    image = db.Column(db.String(100), unique=True)
    num_pages = db.Column(db.Integer)
    pub_date = db.Column(db.DateTime, default=datetime.utcnow())

    # Relationship
    pub_id = db.Column(db.Integer, db.ForeignKey('publication.id'))

    def __init__(self, title, author, avg_rating, book_format, image, num_pages, pub_id):
        self.title = title
        self.author = author
        self.avg_rating = avg_rating
        self.format = book_format
        self.image = image
        self.num_pages = num_pages
        self.pub_id = pub_id

    def __repr__(self):
        return '{} by {}'.format(self.title, self.author)

app/catalog/__init__.py
# app/catalog/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

from app.catalog import routes

app/catalog/routes.py
from app.catalog import main
from app import db
from app.catalog.models import Book, Publication
from flask import render_template


@main.route('/')
def display_books():
    books = Book.query.all()
    return render_template('home.html', books=books)


@main.route('/display/publisher/<publisher_id>')
def display_publisher(publisher_id):
    publisher = Publication.query.filter_by(id=publisher_id).first()
    publisher_books = Book.query.filter_by(pub_id=publisher_id).all()

    return render_template('publisher.html', publisher=publisher, publisher_books=publisher_books)

app/catalog/templates/home.html
{% extends 'layout.html' %}

    {% block content %}
        <div class="container books">
            <div class="row">
                {% for book in books %}
                    <div class="col-md-4">
                        <img src="static/img/{{ book.image }}" alt="book-img" height="200" width="190" class="img-rounded">
                        <h4>Title: {{ book.title }}</h4>
                        <p>Authors: {{ book.author }}</p>
                        <p>Format: {{ book.format }}</p>
                        <p>Rating: {{ book.avg_rating }}</p>
                        <p>Pages: {{ book.num_pages }}</p>
                        <p><a href="{{ url_for('main.display_publisher', publisher_id=book.pub_id) }}">Publisher Id: {{ book.pub_id }}</a></p>
                        <br>
                    </div>
                {% endfor %}
            </div>
        </div>

    {% endblock %}

app/catalog/templates/layout.html
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">

    {# head #}
    {% block head %}
        <head>
            <title> books inc </title>
            <meta charset="UTF-8">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <link href="https://fonts.googleapis.com/css?family=Sansita" rel="stylesheet">
            <link rel="stylesheet" href="{{ url_for('static', filename = 'css/styles.css') }}">
        </head>
    {% endblock head %}

    {# body #}
    {% block body %}
    <body>
    <div class="wrapper">
        {# navigation bar #}
        {% block navbar %}
            <nav class="navbar navbar-inverse">
                <div class="container">
                    <a class="navbar navbar-text" href="{{ url_for('main.display_books') }}">
                        <h3 class="title"> The Books Shop Around the Corner </h3>
                    </a>
                    <ul class="nav navbar-nav pull-right">
                        <li><a href="{{ url_for('main.display_books') }}"> Home </a></li>
                        <li><a href="{{ url_for('authentication.register_user') }}"> Register </a></li>
                        <li> {% if current_user.is_authenticated %}
                                <a href="{{ url_for('authentication.log_out_user') }}"> SignOut </a>
                             {% else %}
                                <a href="{{ url_for('authentication.do_the_login') }}"> SignIn </a>
                             {% endif %}
                        </li>
                        <li>
                            <a href="">
                                {% if current_user.is_authenticated %}
                                    LoggedIn as <b style="color: deeppink">{{ current_user.user_name.title() }}</b>
                                {% else %}
                                    Not LoggedIn
                                {% endif %}
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>
        {% endblock navbar %}

        {# flash messaging #}
        {% for message in get_flashed_messages() %}
                <div class=" container alert alert-info">
                    <button type="button" class="close" data-dismiss="alert"></button>
                    {{ message }}
                </div>
        {% endfor %}

        {# empty block for custom content #}
        {% block content %} {% endblock content %}

        {# footer #}
        {% block footer %}
            <footer>
                <div class="container ftr">
                    <hr>
                    <p class="text-center small">The Shop Around The Corner &copy;  |  2018</p>
                </div>
            </footer>
        {% endblock footer %}

    </div>
    </body>
    {% endblock body %}
</html>

app/catalog/templates/publisher.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container ublisher>">
        <h4>Books by {{ publisher.name }}</h4>
        <ol>
            {% for book in publisher_books %}
                <li type="1">
                    {{ book.title }} by {{ book.author }}
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock content %}